server:
  port: 8090

spring:
  application:
    name: cric-gateway

eureka:
  instance:
    appname: cric-gateway
    lease-renewal-interval-in-seonds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 10

management:
  security:
    enabled: false

logging:
  level:
    com.criapi.gateway: DEBUG

zuul:
  host:
    connect-timeout-mills: 50000
    socket-timeout-mills: 50000